/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.1
 * Generated at: 2022-01-11 05:52:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Reg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Case Study</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("   body {\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("            background-color: rgb(48, 46, 46);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding-top: 25vh;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .container {\r\n");
      out.write("            width: 400px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            background-color: rgb(22, 21, 21);\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            padding: 25px 10px;\r\n");
      out.write("            box-shadow: 0 0 15px rgb(80, 79, 79);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        form {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            width: 90%;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        input {\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            margin: 5px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            background-color: rgb(48, 46, 46);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btns {\r\n");
      out.write("            margin: 15px auto;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        button {\r\n");
      out.write("            background-color: rgb(0, 0, 0);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 8px 30px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            display:block;\r\n");
      out.write("            text-align:center;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        button:hover {\r\n");
      out.write("            background-color: green;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        p {\r\n");
      out.write("            color: red;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("        body,html\r\n");
      out.write("{\r\n");
      out.write(" background-image: url(\"img/img5.jpg\");\r\n");
      out.write(" background-size: 1100px;\r\n");
      out.write("  height: 600px;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("        \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    function Validate() {\r\n");
      out.write("        var password = document.getElementById(\"password\").value;\r\n");
      out.write("        var confirmPassword = document.getElementById(\"confirm_password\").value;\r\n");
      out.write("        if (password != confirmPassword) {\r\n");
      out.write("            alert(\"Passwords do not match.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        return true;\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write(" <div class=\"container\">\r\n");
      out.write("        <h2>Registration</h2>\r\n");
      out.write("        <form action=\"Register1\" method=\"post\">\r\n");
      out.write("            \r\n");
      out.write("            <input type=\"number\" name=\"userid\" id=\"userid\" placeholder=\"User ID\" required>\r\n");
      out.write("            <input type=\"text\" name=\"uname\" id=\"username\" placeholder=\"User Name\" required>\r\n");
      out.write("            <input type=\"email\" name=\"email\" id=\"email\" placeholder=\"Email\" required>\r\n");
      out.write("            <input type=\"mobile_number\" name=\"phone\" id=\"mobileno\" placeholder=\"Mobile No\" required>\r\n");
      out.write("            <input type=\"password\" name=\"password\" id=\"password\" placeholder=\"Password\" required>\r\n");
      out.write("            <input type=\"password\" name=\"confirm_password\" id=\"confirm_password\" placeholder=\" Confirm Password\" required>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"btns\">\r\n");
      out.write("                <button type=\"submit\" value=\"Register1\" id=\"lg\" onclick=\"return Validate()\">Register</button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
